# this is supposed to be used by the code gen but it isn't
[swagger_codegen]
endpoint = "swagger_codegen.parsing.endpoint.EndpointDescription"
renderer = "swagger_codegen.render.renderers.package.PackageRenderer"
#renderer = "swagger_codegen.render.renderers.installable_package.InstallablePackageRenderer"

[services]

# Load api definition from filesystem.
[services.cts]
uri = "src/yaml/cts.yaml"
directory = "/tmp/api"
package = "cts"
